// ============================================================================
// courses/catalog.ts
// ----------------------------------------------------------------------------
// The full catalog of structured piano courses. This is the single source of
// truth for everything the user sees under Practice → Courses.
//
// Structure:
//   * Top-level export is `COURSES_LIST: Course[]` — every course defined in
//     this file, in display order, grouped by category.
//   * Each `Course` contains a sequence of `CourseStep`s (see ./types.ts) that
//     the player UI in `components/courses/` renders one at a time.
//
// Conventions used throughout the catalog:
//   * MIDI constants (C_MAJOR, A_MINOR, G_MAJOR_SCALE, …) come from ./music.ts
//     so courses don't sprinkle magic numbers everywhere.
//   * `highlightKeys` paints specific keys; `highlightAccent` adds a secondary
//     colour (used e.g. to show "every C across the keyboard").
//   * Most steps describe their own demo via the discriminated-union fields
//     (chord, sequence, etc.); only DemoSequenceStep needs explicit timing.
//   * The TOTAL_COURSES constant in `lib/achievements.ts` must match the count
//     in this file — bumping the catalog without updating that const breaks
//     the "Finish every course" achievement.
//
// The file is mostly declarative data; the runtime logic lives in the course
// player components, not here.
// ============================================================================

import {
	A_MINOR,
	A_MINOR_HIGH,
	A_NATURAL_MINOR_SCALE,
	C_BLUES_SCALE,
	C_MAJ7,
	C_MAJOR,
	C_MAJOR_HIGH,
	C_MAJOR_INV1,
	C_MAJOR_INV2,
	C_MAJOR_PENTATONIC,
	C_MAJOR_SCALE,
	C_POSITION_LH,
	C_POSITION_RH,
	C_DOM7,
	F_DOM7,
	G_DOM7,
	D_MINOR,
	E_MINOR,
	F_MAJOR,
	F_MAJOR_HIGH,
	F_MAJOR_SCALE,
	G_MAJOR,
	G_MAJOR_HIGH,
	G_MAJOR_SCALE,
	G_POSITION_RH,
	G7,
	MIDDLE_C,
	midisOfLetterInRange,
	whiteKeysInRange,
} from "./music";
import type { Course } from "./types";

// Pre-computed "every C / D / E / … on the 88-key piano" arrays. Used by the
// "play any C anywhere" style of intro step so the user can hit the note in
// whichever octave they like.
const ALL_CS = midisOfLetterInRange("C", 21, 108);
const ALL_DS = midisOfLetterInRange("D", 21, 108);
const ALL_ES = midisOfLetterInRange("E", 21, 108);
const ALL_FS = midisOfLetterInRange("F", 21, 108);
const ALL_GS = midisOfLetterInRange("G", 21, 108);
const ALL_AS = midisOfLetterInRange("A", 21, 108);
const ALL_BS = midisOfLetterInRange("B", 21, 108);

// Used by the "C# / Db" black-key lesson. Named explicitly because that
// course wants exactly C#4 (not "any C#").
const C_SHARP_4 = 61;

const COURSES_LIST: Course[] = [
	// ── INTRO: Letter Notation ───────────────────────────────────────
	{
		id: "intro-letter-notation",
		category: "intro",
		title: "The Letter Notation",
		description: "Learn the 7 letters of music.",
		estimatedMinutes: 4,
		summary: [
			"Music uses just 7 letters: A B C D E F G",
			"How to find each letter using the black-key groups as landmarks",
			"Played all 7 notes in order from middle C",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "7 letters, that's all",
				body: "Music uses just 7 letters: A B C D E F G. After G, we start over.",
				image: "/courses/letter-notation.svg",
				imageAlt: "One octave with each white key labelled C D E F G A B",
			},
			{
				id: "2",
				type: "text",
				title: "Every white key has a name",
				body: "All the highlighted keys below are C. Each white key is one of the 7 letters.",
				highlightAccent: ALL_CS,
				image: "/courses/letter-notation.svg",
				imageAlt: "Each white key gets one of the 7 letters",
			},
			{
				id: "3",
				type: "play-any-of",
				title: "Press any C",
				body: "C is just before each group of 2 black keys.",
				highlightAccent: ALL_CS,
				allowedMidis: ALL_CS,
				image: "/courses/note-c.svg",
				imageAlt: "C — sits just before the group of 2 black keys",
			},
			{
				id: "4",
				type: "play-any-of",
				title: "Press any D",
				body: "D sits between the 2 black keys.",
				highlightAccent: ALL_DS,
				allowedMidis: ALL_DS,
				image: "/courses/note-d.svg",
				imageAlt: "D — between the 2 black keys",
			},
			{
				id: "5",
				type: "play-any-of",
				title: "Press any E",
				body: "E is just after the 2 black keys.",
				highlightAccent: ALL_ES,
				allowedMidis: ALL_ES,
				image: "/courses/note-e.svg",
				imageAlt: "E — just after the 2 black keys",
			},
			{
				id: "6",
				type: "play-any-of",
				title: "Press any F",
				body: "F is just before each group of 3 black keys.",
				highlightAccent: ALL_FS,
				allowedMidis: ALL_FS,
				image: "/courses/note-f.svg",
				imageAlt: "F — sits just before the group of 3 black keys",
			},
			{
				id: "7",
				type: "play-any-of",
				title: "Press any G",
				body: "G sits between the first two black keys of the group of 3.",
				highlightAccent: ALL_GS,
				allowedMidis: ALL_GS,
				image: "/courses/note-g.svg",
				imageAlt: "G — between the first 2 black keys of the group of 3",
			},
			{
				id: "8",
				type: "play-any-of",
				title: "Press any A",
				body: "A sits between the last two black keys of the group of 3.",
				highlightAccent: ALL_AS,
				allowedMidis: ALL_AS,
				image: "/courses/note-a.svg",
				imageAlt: "A — between the last 2 black keys of the group of 3",
			},
			{
				id: "9",
				type: "play-any-of",
				title: "Press any B",
				body: "B is the last white key before C comes back.",
				highlightAccent: ALL_BS,
				allowedMidis: ALL_BS,
				image: "/courses/note-b.svg",
				imageAlt: "B — the last white key before C returns",
			},
			{
				id: "10",
				type: "play-sequence",
				title: "Play C to C",
				body: "From middle C, play all 7 letters in order, then back to C.",
				sequence: C_MAJOR_SCALE,
				sequenceLabels: ["C", "D", "E", "F", "G", "A", "B", "C"],
				highlightKeys: C_MAJOR_SCALE,
				image: "/courses/c-major-scale.svg",
				imageAlt: "C major scale highlighted",
			},
			{
				id: "11",
				type: "text",
				title: "Nice!",
				body: "You can now name every white key. That's the whole alphabet of music.",
				image: "/courses/letter-notation.svg",
				imageAlt: "One octave with each white key labelled C D E F G A B",
			},
		],
	},

	// ── INTRO: Piano Keys ────────────────────────────────────────────
	{
		id: "intro-piano-keys",
		category: "intro",
		title: "The Piano Keys",
		description: "88 keys, repeated patterns, and middle C.",
		estimatedMinutes: 3,
		summary: [
			"88 keys total: 52 white and 36 black",
			"The 2+3 black-key pattern repeats every octave",
			"Found and played middle C",
			"Black keys are sharps (♯) and flats (♭)",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "88 keys",
				body: "52 white, 36 black. The pattern of 2 + 3 black keys repeats over and over.",
				image: "/courses/octave-pattern.svg",
				imageAlt: "Two octaves showing the repeating 2 + 3 black-key pattern",
			},
			{
				id: "2",
				type: "text",
				title: "Octaves",
				body: "Each repeat of the pattern is one octave. The same letter shows up every octave.",
				highlightAccent: ALL_CS,
				image: "/courses/octave-pattern.svg",
				imageAlt: "Octaves marked — each C starts a new octave",
			},
			{
				id: "3",
				type: "text",
				title: "Middle C",
				body: "The C in the middle of the piano. Your starting point.",
				highlightKeys: [MIDDLE_C],
				image: "/courses/middle-c.svg",
				imageAlt: "Middle C is the C closest to the centre of the keyboard",
			},
			{
				id: "4",
				type: "play-note",
				title: "Press middle C",
				body: "The highlighted key.",
				midi: MIDDLE_C,
				highlightKeys: [MIDDLE_C],
				image: "/courses/middle-c.svg",
				imageAlt: "Middle C is the C closest to the centre of the keyboard",
			},
			{
				id: "5",
				type: "text",
				title: "Black keys = sharps and flats",
				body: "Each black key has TWO names — a sharp (♯) of the white key below, and a flat (♭) of the white key above. C♯ and D♭ are the same key.",
				highlightAccent: [C_SHARP_4],
				image: "/courses/black-keys-sharps-flats.svg",
				imageAlt: "All five black keys in one octave with both their sharp and flat names",
			},
			{
				id: "6",
				type: "play-note",
				title: "Press C♯",
				body: "The black key just right of middle C.",
				midi: C_SHARP_4,
				highlightKeys: [C_SHARP_4],
				image: "/courses/black-keys-sharps-flats.svg",
				imageAlt: "All five black keys in one octave with both their sharp and flat names",
			},
			{
				id: "7",
				type: "play-sequence",
				title: "C in three octaves",
				body: "Low C → middle C → high C.",
				sequence: [48, 60, 72],
				sequenceLabels: ["C3", "C4", "C5"],
				highlightKeys: [48, 60, 72],
				image: "/courses/octave-pattern.svg",
				imageAlt: "C notes across multiple octaves",
			},
		],
	},

	// ── INTRO: Finger Numbers ────────────────────────────────────────
	{
		id: "intro-finger-numbers",
		category: "intro",
		title: "Finger Numbers",
		description: "1 to 5, thumb to pinky.",
		estimatedMinutes: 3,
		summary: ["Thumb = 1, pinky = 5 — same on both hands", "Played C D E with fingers 1-2-3", "Walked all 5 fingers up and down"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Thumb = 1, pinky = 5",
				body: "Thumb is 1. Index 2. Middle 3. Ring 4. Pinky 5. Same on both hands.",
				image: "/courses/piano_fingers.png",
				imageAlt: "Both hands with each finger labelled 1 (thumb) through 5 (pinky)",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Right thumb on C",
				body: "Press middle C with your thumb (finger 1).",
				image: "/courses/piano_fingers.png",
				imageAlt: "Both hands with each finger labelled 1 (thumb) through 5 (pinky)",
				sequence: [MIDDLE_C],
				sequenceLabels: ["1"],
				highlightKeys: [MIDDLE_C],
			},
			{
				id: "3",
				type: "play-sequence",
				title: "1 · 2 · 3",
				body: "C with thumb, D with index, E with middle.",
				sequence: [60, 62, 64],
				sequenceLabels: ["1", "2", "3"],
				highlightKeys: [60, 62, 64],
				image: "/courses/piano_fingers.png",
				imageAlt: "Both hands with each finger labelled 1 (thumb) through 5 (pinky)",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "All five fingers",
				body: "Walk up and down: 1 2 3 4 5 5 4 3 2 1.",
				sequence: [60, 62, 64, 65, 67, 67, 65, 64, 62, 60],
				sequenceLabels: ["1", "2", "3", "4", "5", "5", "4", "3", "2", "1"],
				highlightKeys: C_POSITION_RH,
				image: "/courses/piano_fingers.png",
				imageAlt: "Both hands with each finger labelled 1 (thumb) through 5 (pinky)",
			},
		],
	},

	// ── INTRO: C Position Right Hand ─────────────────────────────────
	{
		id: "intro-c-position-rh",
		category: "intro",
		title: "C Position — Right Hand",
		description: "Park 5 fingers on 5 keys.",
		estimatedMinutes: 3,
		summary: ["Right thumb on middle C, pinky on G", "Walked C-D-E-F-G up and back", "Skipped notes with fingers 1, 3, 5"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "C position",
				body: "Right thumb on middle C. Other fingers fall on D E F G.",
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand C position — thumb (1) on C, pinky (5) on G",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Walk up",
				body: "C D E F G.",
				sequence: C_POSITION_RH,
				sequenceLabels: ["1", "2", "3", "4", "5"],
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand C position — thumb (1) on C, pinky (5) on G",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Walk down",
				body: "G F E D C.",
				sequence: [67, 65, 64, 62, 60],
				sequenceLabels: ["5", "4", "3", "2", "1"],
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand C position — thumb (1) on C, pinky (5) on G",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Skip notes",
				body: "Try fingers 1, 3, 5: C E G.",
				sequence: [60, 64, 67],
				sequenceLabels: ["1", "3", "5"],
				highlightKeys: [60, 64, 67],
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand C position — thumb (1) on C, pinky (5) on G",
			},
		],
	},

	// ── INTRO: C Position Left Hand ──────────────────────────────────
	{
		id: "intro-c-position-lh",
		category: "intro",
		title: "C Position — Left Hand",
		description: "Same five keys, an octave lower.",
		estimatedMinutes: 3,
		summary: [
			"Left pinky on C3, thumb on G3 — one octave below the right hand",
			"Walked the same five notes with the left hand",
			"Played a left-hand C major chord",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Same notes, lower",
				body: "Left pinky on C3, thumb on G3. Same five-note shape as the right hand.",
				highlightKeys: C_POSITION_LH,
				image: "/courses/c-position-lh.svg",
				imageAlt: "Left hand C position — pinky (5) on C, thumb (1) on G",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Walk up",
				body: "Left hand: C D E F G (fingers 5 4 3 2 1).",
				sequence: C_POSITION_LH,
				sequenceLabels: ["5", "4", "3", "2", "1"],
				highlightKeys: C_POSITION_LH,
				image: "/courses/c-position-lh.svg",
				imageAlt: "Left hand C position — pinky (5) on C, thumb (1) on G",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Walk down",
				body: "G F E D C.",
				sequence: [55, 53, 52, 50, 48],
				sequenceLabels: ["1", "2", "3", "4", "5"],
				highlightKeys: C_POSITION_LH,
				image: "/courses/c-position-lh.svg",
				imageAlt: "Left hand C position — pinky (5) on C, thumb (1) on G",
			},
			{
				id: "4",
				type: "play-chord",
				title: "Left-hand C chord",
				body: "Hold C, E, G together with fingers 5, 3, 1.",
				midis: [48, 52, 55],
				chordName: "C (LH)",
				highlightKeys: [48, 52, 55],
				image: "/courses/c-position-lh.svg",
				imageAlt: "Left hand C position — pinky (5) on C, thumb (1) on G",
			},
		],
	},

	// ── INTRO: Mary Had a Little Lamb ────────────────────────────────
	{
		id: "intro-mary-had-a-little-lamb",
		category: "intro",
		title: "Your First Song",
		description: "Mary Had a Little Lamb — right hand only.",
		estimatedMinutes: 4,
		summary: [
			"Played 'Mary Had a Little Lamb' on the piano",
			"The whole song fits inside C position — 5 keys",
			"Combined three short phrases into a real tune",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Right hand on C position",
				body: "Thumb on middle C. The whole song uses just these 5 keys.",
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand C position — Mary uses only these 5 keys",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Mary had a little lamb",
				body: "E D C D E E E.",
				sequence: [64, 62, 60, 62, 64, 64, 64],
				sequenceLabels: ["E", "D", "C", "D", "E", "E", "E"],
				highlightKeys: C_POSITION_RH,
				bpm: 70,
				image: "/courses/mary-melody.svg",
				imageAlt: "Use only C, D, E — press in order: E D C D E E E (F and G are NOT used)",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Little lamb…",
				body: "D D D, then E G G.",
				sequence: [62, 62, 62, 64, 67, 67],
				sequenceLabels: ["D", "D", "D", "E", "G", "G"],
				highlightKeys: C_POSITION_RH,
				bpm: 70,
				image: "/courses/mary-phrase-2.svg",
				imageAlt: "Now G joins in — press in order: D D D E G G (F is still skipped)",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Whose fleece was white as snow",
				body: "E D C D E E E E D D E D C.",
				sequence: [64, 62, 60, 62, 64, 64, 64, 64, 62, 62, 64, 62, 60],
				sequenceLabels: ["E", "D", "C", "D", "E", "E", "E", "E", "D", "D", "E", "D", "C"],
				highlightKeys: C_POSITION_RH,
				bpm: 70,
				image: "/courses/mary-melody.svg",
				imageAlt: "Back to C, D, E — sequence: E D C D E E E E D D E D C",
			},
			{
				id: "5",
				type: "text",
				title: "You played a song!",
				body: "5 keys, one hand, real music. Now let's try the whole thing at once.",
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand C position — Mary uses only these 5 keys",
			},
			{
				id: "6",
				type: "play-sequence",
				title: "The Whole Song",
				body: "Put it all together from start to finish.",
				sequence: [64, 62, 60, 62, 64, 64, 64, 62, 62, 62, 64, 67, 67, 64, 62, 60, 62, 64, 64, 64, 64, 62, 62, 64, 62, 60],
				sequenceLabels: [
					"E",
					"D",
					"C",
					"D",
					"E",
					"E",
					"E",
					"D",
					"D",
					"D",
					"E",
					"G",
					"G",
					"E",
					"D",
					"C",
					"D",
					"E",
					"E",
					"E",
					"E",
					"D",
					"D",
					"E",
					"D",
					"C",
				],
				highlightKeys: C_POSITION_RH,
				bpm: 70,
				image: "/courses/c-position-rh.svg",
				imageAlt: "All 5 C-position keys — the whole song lives here",
			},
		],
	},

	// ── SCALES: G Major ──────────────────────────────────────────────
	{
		id: "scales-g-major",
		category: "scales",
		title: "G Major Scale",
		description: "One black key — F♯.",
		estimatedMinutes: 3,
		summary: ["G major scale: G A B C D E F♯ G", "One black key — F♯ — replaces F", "Played the scale up and back down"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "G to G",
				body: "G A B C D E F♯ G. Just one black key: F♯.",
				highlightKeys: G_MAJOR_SCALE,
				image: "/courses/g-major-scale.svg",
				imageAlt: "G major scale highlighted on the keyboard — F♯ is the one black key",
			},
			{
				id: "2",
				type: "play-note",
				title: "Find F♯",
				body: "The black key just right of F.",
				midi: 66,
				highlightKeys: [66],
				image: "/courses/g-major-scale.svg",
				imageAlt: "G major scale highlighted on the keyboard — F♯ is the one black key",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Play it up",
				body: "G A B C D E F♯ G.",
				sequence: G_MAJOR_SCALE,
				sequenceLabels: ["G", "A", "B", "C", "D", "E", "F♯", "G"],
				highlightKeys: G_MAJOR_SCALE,
				image: "/courses/g-major-scale.svg",
				imageAlt: "G major scale highlighted on the keyboard — F♯ is the one black key",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Play it down",
				body: "G F♯ E D C B A G.",
				sequence: [67, 66, 64, 62, 60, 59, 57, 55],
				sequenceLabels: ["G", "F♯", "E", "D", "C", "B", "A", "G"],
				highlightKeys: G_MAJOR_SCALE,
				image: "/courses/g-major-scale.svg",
				imageAlt: "G major scale highlighted on the keyboard — F♯ is the one black key",
			},
		],
	},

	// ── SCALES: F Major ──────────────────────────────────────────────
	{
		id: "scales-f-major",
		category: "scales",
		title: "F Major Scale",
		description: "One black key — B♭.",
		estimatedMinutes: 3,
		summary: ["F major scale: F G A B♭ C D E F", "One black key — B♭ — replaces B", "Played the scale up and back down"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "F to F",
				body: "F G A B♭ C D E F. The black key is B♭.",
				highlightKeys: F_MAJOR_SCALE,
				image: "/courses/f-major-scale.svg",
				imageAlt: "F major scale highlighted — B♭ is the one black key",
			},
			{
				id: "2",
				type: "play-note",
				title: "Find B♭",
				body: "The black key just left of B.",
				midi: 58,
				highlightKeys: [58],
				image: "/courses/f-major-scale.svg",
				imageAlt: "F major scale highlighted — B♭ is the one black key",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Play it up",
				body: "F G A B♭ C D E F.",
				sequence: F_MAJOR_SCALE,
				sequenceLabels: ["F", "G", "A", "B♭", "C", "D", "E", "F"],
				highlightKeys: F_MAJOR_SCALE,
				image: "/courses/f-major-scale.svg",
				imageAlt: "F major scale highlighted — B♭ is the one black key",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Play it down",
				body: "F E D C B♭ A G F.",
				sequence: [65, 64, 62, 60, 58, 57, 55, 53],
				sequenceLabels: ["F", "E", "D", "C", "B♭", "A", "G", "F"],
				highlightKeys: F_MAJOR_SCALE,
				image: "/courses/f-major-scale.svg",
				imageAlt: "F major scale highlighted — B♭ is the one black key",
			},
		],
	},

	// ── SCALES: A Natural Minor ──────────────────────────────────────
	{
		id: "scales-a-minor",
		category: "scales",
		title: "A Minor Scale",
		description: "All white keys — but sounds sad.",
		estimatedMinutes: 3,
		summary: ["A minor uses the same 7 white keys as C major", "Starting on A gives a sad mood instead of happy", "Played the A minor chord (A C E)"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Same keys, different start",
				body: "All white keys from A to A. Same notes as C major — sounds sad.",
				highlightKeys: A_NATURAL_MINOR_SCALE,
				image: "/courses/a-minor-scale.svg",
				imageAlt: "A natural minor scale — all white keys from A to A, W-H-W-W-H-W-W pattern",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Play it",
				body: "A B C D E F G A.",
				sequence: A_NATURAL_MINOR_SCALE,
				sequenceLabels: ["A", "B", "C", "D", "E", "F", "G", "A"],
				highlightKeys: A_NATURAL_MINOR_SCALE,
				image: "/courses/a-minor-scale.svg",
				imageAlt: "A minor uses the same 7 white keys — starting on A gives a sad mood",
			},
			{
				id: "3",
				type: "play-chord",
				title: "A minor chord",
				body: "A, C, E together. Listen — dark and sad.",
				midis: A_MINOR,
				chordName: "Am",
				highlightKeys: A_MINOR,
				image: "/courses/a-minor-scale.svg",
				imageAlt: "A minor uses the same 7 white keys — starting on A gives a sad mood",
			},
			{
				id: "4",
				type: "text",
				title: "Major or minor?",
				body: "Start on C: happy. Start on A: sad. Same 7 white keys.",
				image: "/courses/a-minor-scale.svg",
				imageAlt: "A minor uses the same 7 white keys — starting on A gives a sad mood",
			},
		],
	},

	// ── SCALES: Pentatonic ───────────────────────────────────────────
	{
		id: "scales-c-pentatonic",
		category: "scales",
		title: "Pentatonic Scale",
		description: "5 notes, no wrong notes.",
		estimatedMinutes: 3,
		summary: [
			"C major pentatonic: C D E G A (5 notes)",
			"Drop the F and B from the major scale to get it",
			"Free-played 8 notes with no wrong choices",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "5 notes only",
				body: "C D E G A. We dropped the F and B from the major scale.",
				highlightKeys: C_MAJOR_PENTATONIC,
				image: "/courses/pentatonic-scale.svg",
				imageAlt: "C major pentatonic — C D E G A (F and B dimmed out)",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Walk it up",
				body: "C D E G A C.",
				sequence: C_MAJOR_PENTATONIC,
				sequenceLabels: ["C", "D", "E", "G", "A", "C"],
				highlightKeys: C_MAJOR_PENTATONIC,
				image: "/courses/pentatonic-scale.svg",
				imageAlt: "C major pentatonic — C D E G A (F and B dimmed out)",
			},
			{
				id: "3",
				type: "play-any-of",
				title: "Free play — 8 keys",
				body: "Mash any of the highlighted keys. Anything works.",
				allowedMidis: [60, 62, 64, 67, 69, 72, 74, 76, 79, 81, 84],
				hitsNeeded: 8,
				highlightKeys: C_MAJOR_PENTATONIC,
				image: "/courses/pentatonic-scale.svg",
				imageAlt: "C major pentatonic — C D E G A (F and B dimmed out)",
			},
		],
	},

	// ── HAND INDEPENDENCE: Right Hand 1 ──────────────────────────────
	{
		id: "hand-rh-1",
		category: "hand_independence",
		title: "Right Hand Exercise 1",
		description: "Stay in C position.",
		estimatedMinutes: 2,
		summary: ["Right hand patterns inside C position", "Walked up-two-back-two and full position", "Practised skipping notes (C E G)"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Right hand only",
				body: "Hand on C position. Keep it relaxed.",
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand in C position",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Up two, back two",
				body: "C D E D C.",
				sequence: [60, 62, 64, 62, 60],
				sequenceLabels: ["C", "D", "E", "D", "C"],
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand in C position",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Up five, back five",
				body: "Up to G, back to C.",
				sequence: [60, 62, 64, 65, 67, 65, 64, 62, 60],
				sequenceLabels: ["1", "2", "3", "4", "5", "4", "3", "2", "1"],
				highlightKeys: C_POSITION_RH,
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand in C position",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Skip notes",
				body: "C E G E C.",
				sequence: [60, 64, 67, 64, 60],
				sequenceLabels: ["1", "3", "5", "3", "1"],
				highlightKeys: [60, 64, 67],
				image: "/courses/c-position-rh.svg",
				imageAlt: "Right hand in C position",
			},
		],
	},

	// ── HAND INDEPENDENCE: Right Hand 2 ──────────────────────────────
	{
		id: "hand-rh-2",
		category: "hand_independence",
		title: "Right Hand Exercise 2",
		description: "Shift from C to G position.",
		estimatedMinutes: 3,
		summary: ["G position: right thumb on G4, pinky on D5", "Practised walking the G position", "Shifted the whole hand from C to G"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "New home: G position",
				body: "Thumb on G4, pinky on D5.",
				highlightKeys: G_POSITION_RH,
				image: "/courses/g-position-rh.svg",
				imageAlt: "Right hand in G position",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Walk G position",
				body: "G A B C D.",
				sequence: G_POSITION_RH,
				sequenceLabels: ["G", "A", "B", "C", "D"],
				highlightKeys: G_POSITION_RH,
				image: "/courses/g-position-rh.svg",
				imageAlt: "Right hand in G position",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "And back",
				body: "D C B A G.",
				sequence: [74, 72, 71, 69, 67],
				sequenceLabels: ["D", "C", "B", "A", "G"],
				highlightKeys: G_POSITION_RH,
				image: "/courses/g-position-rh.svg",
				imageAlt: "Right hand in G position",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Position shift",
				body: "C-position then G-position. Move your whole hand up.",
				sequence: [60, 62, 64, 65, 67, 67, 69, 71, 72, 74],
				sequenceLabels: ["C", "D", "E", "F", "G", "G", "A", "B", "C", "D"],
				highlightKeys: [...C_POSITION_RH, ...G_POSITION_RH],
				image: "/courses/g-position-rh.svg",
				imageAlt: "Right hand in G position",
			},
		],
	},

	// ── HAND INDEPENDENCE: Left Hand 1 ───────────────────────────────
	{
		id: "hand-lh-1",
		category: "hand_independence",
		title: "Left Hand Exercise 1",
		description: "Bass notes.",
		estimatedMinutes: 2,
		summary: [
			"Left hand plays the bass (lowest note of each chord)",
			"Walked bass roots: C, A, F, G",
			"Combined bass note then full chord — basic accompaniment shape",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Left hand = bass",
				body: "The left hand plays the lowest note of each chord.",
				highlightKeys: [48, 45, 41, 43],
				image: "/courses/bass-notes.svg",
				imageAlt: "Left hand playing bass notes",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "C A F G",
				body: "Four bass notes, one at a time.",
				sequence: [48, 45, 41, 43],
				sequenceLabels: ["C", "A", "F", "G"],
				highlightKeys: [48, 45, 41, 43],
				image: "/courses/bass-notes.svg",
				imageAlt: "Left hand playing bass notes",
			},
			{
				id: "3",
				type: "play-chord",
				title: "Left-hand C chord",
				body: "C E G together.",
				midis: C_MAJOR,
				chordName: "C (LH)",
				highlightKeys: C_MAJOR,
				image: "/courses/bass-notes.svg",
				imageAlt: "Left hand playing bass notes",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Bass + chord",
				body: "Bass C, then the full chord.",
				sequence: [48, C_MAJOR],
				sequenceLabels: ["bass", "chord"],
				highlightKeys: [48, ...C_MAJOR],
				image: "/courses/bass-notes.svg",
				imageAlt: "Left hand playing bass notes",
			},
		],
	},

	// ── HAND INDEPENDENCE: Both Hands Scale ──────────────────────────
	{
		id: "hand-both-scale",
		category: "hand_independence",
		title: "Both Hands Together",
		description: "C major scale, both hands.",
		estimatedMinutes: 4,
		summary: [
			"Played both hands at the same time",
			"C major scale spanning two octaves (LH C3-C4, RH C4-C5)",
			"Left and right hands stayed in sync note-for-note",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Same scale, two octaves apart",
				body: "Right hand C4-C5. Left hand C3-C4. Same notes, lower octave.",
				highlightKeys: [...C_MAJOR_SCALE, 48, 50, 52, 53, 55, 57, 59],
				image: "/courses/hand-independence.svg",
				imageAlt: "Left hand plays the lower C position, right hand plays the higher one",
			},
			{
				id: "2",
				type: "play-chord",
				title: "Both Cs",
				body: "C3 and C4 together.",
				midis: [48, 60],
				chordName: "C octave",
				highlightKeys: [48, 60],
				image: "/courses/hand-independence.svg",
				imageAlt: "Left hand plays the lower C position, right hand plays the higher one",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "First two notes",
				body: "C + C, then D + D.",
				sequence: [
					[48, 60],
					[50, 62],
				],
				sequenceLabels: ["C", "D"],
				highlightKeys: [48, 50, 60, 62],
				image: "/courses/hand-independence.svg",
				imageAlt: "Left hand plays the lower C position, right hand plays the higher one",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Whole scale, both hands",
				body: "C D E F G A B C — both hands at once.",
				sequence: [
					[48, 60],
					[50, 62],
					[52, 64],
					[53, 65],
					[55, 67],
					[57, 69],
					[59, 71],
					[60, 72],
				],
				sequenceLabels: ["C", "D", "E", "F", "G", "A", "B", "C"],
				highlightKeys: [...C_MAJOR_SCALE, 48, 50, 52, 53, 55, 57, 59],
				bpm: 70,
				image: "/courses/hand-independence.svg",
				imageAlt: "Left hand plays the lower C position, right hand plays the higher one",
			},
		],
	},

	// ── CHORDS: What is a Chord ──────────────────────────────────────
	{
		id: "chords-what-is-a-chord",
		category: "chords",
		title: "What is a Chord",
		description: "C, F, G, and A minor.",
		estimatedMinutes: 4,
		summary: [
			"A chord = 2 or more notes played together (most use 3)",
			"Played C major, F major, G major",
			"Played A minor — sounds sad",
			"The four magic chords: C → Am → F → G",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Two or more notes",
				body: "A chord = 2 or more notes played together. Most use 3.",
				image: "/courses/c-major-chord.svg",
				imageAlt: "C major chord shape — C, E, G",
			},
			{
				id: "2",
				type: "text",
				title: "C major",
				body: "C, E, G. Every other white key starting from C.",
				highlightKeys: C_MAJOR,
				image: "/courses/c-major-chord.svg",
				imageAlt: "C major chord shape — C, E, G",
			},
			{
				id: "3",
				type: "play-chord",
				title: "Play C major",
				body: "Press C, E, G together.",
				midis: C_MAJOR,
				chordName: "C",
				highlightKeys: C_MAJOR,
				image: "/courses/c-major-chord.svg",
				imageAlt: "C major — C, E, G",
			},
			{
				id: "4",
				type: "play-chord",
				title: "Play F major",
				body: "F, A, C. Same idea, starting on F.",
				midis: F_MAJOR,
				chordName: "F",
				highlightKeys: F_MAJOR,
				image: "/courses/f-major-chord.svg",
				imageAlt: "F major — F, A, C",
			},
			{
				id: "5",
				type: "play-chord",
				title: "Play G major",
				body: "G, B, D.",
				midis: G_MAJOR,
				chordName: "G",
				highlightKeys: G_MAJOR,
				image: "/courses/g-major-chord.svg",
				imageAlt: "G major — G, B, D",
			},
			{
				id: "6",
				type: "play-chord",
				title: "Play A minor",
				body: "A, C, E. Listen — it sounds sad.",
				midis: A_MINOR,
				chordName: "Am",
				highlightKeys: A_MINOR,
				image: "/courses/a-minor-chord.svg",
				imageAlt: "A minor — A, C, E",
			},
			{
				id: "7",
				type: "play-sequence",
				title: "The four magic chords",
				body: "C → Am → F → G. These four are in thousands of pop songs.",
				sequence: [C_MAJOR, A_MINOR, F_MAJOR, G_MAJOR],
				sequenceLabels: ["C", "Am", "F", "G"],
				bpm: 80,
				image: "/courses/i-iv-v.svg",
				imageAlt: "I, IV, V — the three-chord backbone: C, F, G",
			},
		],
	},

	// ── CHORDS: Major vs Minor ───────────────────────────────────────
	{
		id: "chords-major-vs-minor",
		category: "chords",
		title: "Major vs Minor",
		description: "One note changes the mood.",
		estimatedMinutes: 3,
		summary: [
			"Lowering the middle note a half step turns major into minor",
			"Heard C major vs C minor side-by-side",
			"Played the all-white-key minor chords: D minor and E minor",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "The middle note decides",
				body: "Move the middle note of a chord down a half step → major becomes minor.",
				image: "/courses/major-vs-minor.svg",
				imageAlt: "C major vs C minor — the third (E) drops to E♭",
			},
			{
				id: "2",
				type: "play-chord",
				title: "C major (happy)",
				body: "C, E, G.",
				midis: C_MAJOR,
				chordName: "C",
				highlightKeys: C_MAJOR,
				image: "/courses/c-major-chord.svg",
				imageAlt: "C major chord",
			},
			{
				id: "3",
				type: "play-chord",
				title: "C minor (sad)",
				body: "C, E♭, G. We lowered the E to E♭.",
				midis: [48, 51, 55],
				chordName: "Cm",
				highlightKeys: [48, 51, 55],
				image: "/courses/c-minor-chord.svg",
				imageAlt: "C minor chord",
			},
			{
				id: "4",
				type: "play-chord",
				title: "D minor",
				body: "D, F, A — all white keys.",
				midis: D_MINOR,
				chordName: "Dm",
				highlightKeys: D_MINOR,
				image: "/courses/d-minor-chord.svg",
				imageAlt: "D minor — D, F, A",
			},
			{
				id: "5",
				type: "play-chord",
				title: "E minor",
				body: "E, G, B.",
				midis: E_MINOR,
				chordName: "Em",
				highlightKeys: E_MINOR,
				image: "/courses/e-minor-chord.svg",
				imageAlt: "E minor — E, G, B",
			},
		],
	},

	// ── CHORDS: Inversions ───────────────────────────────────────────
	{
		id: "chords-inversions",
		category: "chords",
		title: "Chord Inversions",
		description: "Same chord, different bass note.",
		estimatedMinutes: 3,
		summary: [
			"Same 3 notes in a different order = same chord",
			"Played C in root, 1st, and 2nd inversion",
			"Climbed an octave smoothly through the inversions",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Rearrange the notes",
				body: "C, E, G is C major. So is E, G, C. Same notes, different order.",
				image: "/courses/chord-inversions.svg",
				imageAlt: "C major in root, 1st, and 2nd inversion",
			},
			{
				id: "2",
				type: "play-chord",
				title: "Root: C E G",
				body: "Lowest note is C.",
				midis: C_MAJOR,
				chordName: "C",
				highlightKeys: C_MAJOR,
				image: "/courses/chord-inversions.svg",
				imageAlt: "C major in root, 1st, and 2nd inversion",
			},
			{
				id: "3",
				type: "play-chord",
				title: "1st inversion: E G C",
				body: "Move C up to the top.",
				midis: C_MAJOR_INV1,
				chordName: "C/E",
				highlightKeys: C_MAJOR_INV1,
				image: "/courses/chord-inversions.svg",
				imageAlt: "C major in root, 1st, and 2nd inversion",
			},
			{
				id: "4",
				type: "play-chord",
				title: "2nd inversion: G C E",
				body: "Now G is the lowest note.",
				midis: C_MAJOR_INV2,
				chordName: "C/G",
				highlightKeys: C_MAJOR_INV2,
				image: "/courses/chord-inversions.svg",
				imageAlt: "C major in root, 1st, and 2nd inversion",
			},
			{
				id: "5",
				type: "play-sequence",
				title: "Climb the inversions",
				body: "Root → 1st → 2nd → root (octave up).",
				sequence: [C_MAJOR, C_MAJOR_INV1, C_MAJOR_INV2, [60, 64, 67]],
				sequenceLabels: ["root", "1st", "2nd", "root"],
				image: "/courses/chord-inversions.svg",
				imageAlt: "C major in root, 1st, and 2nd inversion",
			},
		],
	},

	// ── CHORDS: 7th Chords ───────────────────────────────────────────
	{
		id: "chords-sevenths",
		category: "chords",
		title: "7th Chords",
		description: "Add one note, sound jazzier.",
		estimatedMinutes: 3,
		summary: [
			"Stack one more note on a triad to get a 7th chord",
			"Played Cmaj7 (C E G B) and G7 (G B D F)",
			"Heard the tension of G7 resolve back home to C",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Stack one more note",
				body: "C E G is a triad. Add B and you get C E G B — a 7th chord.",
				highlightKeys: C_MAJ7,
				image: "/courses/seventh-chords.svg",
				imageAlt: "Cmaj7 — add B on top of C major",
			},
			{
				id: "2",
				type: "play-chord",
				title: "C major 7",
				body: "C E G B. Dreamy, jazzy.",
				midis: C_MAJ7,
				chordName: "Cmaj7",
				highlightKeys: C_MAJ7,
				image: "/courses/seventh-chords.svg",
				imageAlt: "Cmaj7 — add B on top of C major",
			},
			{
				id: "3",
				type: "play-chord",
				title: "G7",
				body: "G B D F. Sounds unstable — wants to resolve.",
				midis: G7,
				chordName: "G7",
				highlightKeys: G7,
				image: "/courses/g7-chord.svg",
				imageAlt: "G7 chord",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "G7 → C",
				body: "Feel the pull from tension to home.",
				sequence: [G7, C_MAJOR_HIGH],
				sequenceLabels: ["G7", "C"],
				image: "/courses/g7-chord.svg",
				imageAlt: "G7 chord",
			},
		],
	},

	// ── CHORDS: I-IV-V ───────────────────────────────────────────────
	{
		id: "chords-i-iv-v",
		category: "chords",
		title: "I — IV — V",
		description: "The three chord backbone.",
		estimatedMinutes: 4,
		summary: ["The 3-chord backbone: I, IV, V", "In C major that's C, F, G", "Played the I → IV → V → I loop"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Three chords",
				body: "In C major: I = C, IV = F, V = G.",
				image: "/courses/i-iv-v.svg",
				imageAlt: "I, IV, V — the three-chord backbone: C, F, G",
			},
			{
				id: "2",
				type: "play-chord",
				title: "I = C",
				body: "Home.",
				midis: C_MAJOR_HIGH,
				chordName: "C",
				highlightKeys: C_MAJOR_HIGH,
				image: "/courses/i-iv-v.svg",
				imageAlt: "I, IV, V — the three-chord backbone: C, F, G",
			},
			{
				id: "3",
				type: "play-chord",
				title: "IV = F",
				body: "F A C. The lift.",
				midis: F_MAJOR_HIGH,
				chordName: "F",
				highlightKeys: F_MAJOR_HIGH,
				image: "/courses/i-iv-v.svg",
				imageAlt: "I, IV, V — the three-chord backbone: C, F, G",
			},
			{
				id: "4",
				type: "play-chord",
				title: "V = G",
				body: "G B D. The tension.",
				midis: G_MAJOR_HIGH,
				chordName: "G",
				highlightKeys: G_MAJOR_HIGH,
				image: "/courses/i-iv-v.svg",
				imageAlt: "I, IV, V — the three-chord backbone: C, F, G",
			},
			{
				id: "5",
				type: "play-sequence",
				title: "Play the loop",
				body: "C → F → G → C.",
				sequence: [C_MAJOR_HIGH, F_MAJOR_HIGH, G_MAJOR_HIGH, C_MAJOR_HIGH],
				sequenceLabels: ["I", "IV", "V", "I"],
				bpm: 80,
				image: "/courses/i-iv-v.svg",
				imageAlt: "I, IV, V — the three-chord backbone: C, F, G",
			},
		],
	},

	// ── CHORDS: Pop Progression ──────────────────────────────────────
	{
		id: "chords-pop-progression",
		category: "chords",
		title: "Pop Progression",
		description: "The four chords behind countless hits.",
		estimatedMinutes: 4,
		summary: ["The pop loop: vi → IV → I → V", "In C: Am → F → C → G", "This progression drives countless pop songs"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "vi — IV — I — V",
				body: "In C: Am, F, C, G. Used in 'Let It Be', 'Don't Stop Believin'', and many more.",
				image: "/courses/pop-progression.svg",
				imageAlt: "The vi-IV-I-V pop loop: Am, F, C, G",
			},
			{
				id: "2",
				type: "play-chord",
				title: "Am",
				body: "A C E.",
				midis: A_MINOR_HIGH,
				chordName: "Am",
				highlightKeys: A_MINOR_HIGH,
				image: "/courses/pop-progression.svg",
				imageAlt: "The vi-IV-I-V pop loop: Am, F, C, G",
			},
			{
				id: "3",
				type: "play-chord",
				title: "F",
				body: "F A C.",
				midis: F_MAJOR_HIGH,
				chordName: "F",
				highlightKeys: F_MAJOR_HIGH,
				image: "/courses/pop-progression.svg",
				imageAlt: "The vi-IV-I-V pop loop: Am, F, C, G",
			},
			{
				id: "4",
				type: "play-chord",
				title: "C",
				body: "C E G.",
				midis: C_MAJOR_HIGH,
				chordName: "C",
				highlightKeys: C_MAJOR_HIGH,
				image: "/courses/pop-progression.svg",
				imageAlt: "The vi-IV-I-V pop loop: Am, F, C, G",
			},
			{
				id: "5",
				type: "play-chord",
				title: "G",
				body: "G B D.",
				midis: G_MAJOR_HIGH,
				chordName: "G",
				highlightKeys: G_MAJOR_HIGH,
				image: "/courses/pop-progression.svg",
				imageAlt: "The vi-IV-I-V pop loop: Am, F, C, G",
			},
			{
				id: "6",
				type: "play-sequence",
				title: "Loop it",
				body: "Am → F → C → G, twice.",
				sequence: [A_MINOR_HIGH, F_MAJOR_HIGH, C_MAJOR_HIGH, G_MAJOR_HIGH, A_MINOR_HIGH, F_MAJOR_HIGH, C_MAJOR_HIGH, G_MAJOR_HIGH],
				sequenceLabels: ["Am", "F", "C", "G", "Am", "F", "C", "G"],
				bpm: 80,
				image: "/courses/pop-progression.svg",
				imageAlt: "The vi-IV-I-V pop loop: Am, F, C, G",
			},
		],
	},

	// ── INTERVALS: C Major Scale ─────────────────────────────────────
	{
		id: "intervals-c-major-scale",
		category: "intervals",
		title: "Intervals & C Major Scale",
		description: "Half steps, whole steps.",
		estimatedMinutes: 4,
		summary: ["Half step = the next key. Whole step = skip one", "Major scale recipe: W W H W W W H", "Played C major up and down"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Half step",
				body: "One key to the next. Black or white, doesn't matter.",
				image: "/courses/intervals-half-whole.svg",
				imageAlt: "Half step (C → C♯) vs whole step (C → D)",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "C → C♯",
				body: "C, then the black key right of it.",
				sequence: [MIDDLE_C, C_SHARP_4],
				sequenceLabels: ["C", "C♯"],
				highlightKeys: [MIDDLE_C, C_SHARP_4],
				image: "/courses/intervals-half-whole.svg",
				imageAlt: "Half step (C → C♯) vs whole step (C → D)",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "Whole step: C → D",
				body: "Two half steps. Skip the black key.",
				sequence: [MIDDLE_C, 62],
				sequenceLabels: ["C", "D"],
				highlightKeys: [MIDDLE_C, 62],
				image: "/courses/intervals-half-whole.svg",
				imageAlt: "Half step (C → C♯) vs whole step (C → D)",
			},
			{
				id: "4",
				type: "text",
				title: "Major scale recipe",
				body: "W W H W W W H. Apply it from C — that's the C major scale.",
				highlightKeys: C_MAJOR_SCALE,
				image: "/courses/c-major-scale.svg",
				imageAlt: "C major scale with W (whole) and H (half) step pattern",
			},
			{
				id: "5",
				type: "play-sequence",
				title: "Play C major",
				body: "C D E F G A B C.",
				sequence: C_MAJOR_SCALE,
				sequenceLabels: ["C", "D", "E", "F", "G", "A", "B", "C"],
				highlightKeys: C_MAJOR_SCALE,
				image: "/courses/c-major-scale.svg",
				imageAlt: "C major scale with W (whole) and H (half) step pattern",
			},
			{
				id: "6",
				type: "play-sequence",
				title: "Going down",
				body: "C B A G F E D C.",
				sequence: [72, 71, 69, 67, 65, 64, 62, 60],
				sequenceLabels: ["C", "B", "A", "G", "F", "E", "D", "C"],
				highlightKeys: C_MAJOR_SCALE,
				image: "/courses/c-major-scale.svg",
				imageAlt: "C major scale with W (whole) and H (half) step pattern",
			},
		],
	},

	// ── INTERVALS: Ear Training ──────────────────────────────────────
	{
		id: "intervals-ear-training",
		category: "intervals",
		title: "Hear the Intervals",
		description: "Octave, 5th, major 3rd, minor 3rd.",
		estimatedMinutes: 4,
		summary: [
			"Four key intervals: octave, perfect 5th, major 3rd, minor 3rd",
			"Each interval has a distinct sound and feel",
			"Heard the difference between major and minor 3rd",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Same note, different pitch",
				body: "An interval is the distance between two notes.",
				image: "/courses/interval-ear.svg",
				imageAlt: "Four common intervals: octave, fifth, major 3rd, minor 3rd",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Octave: C → C",
				body: "Same letter, 8 white keys apart.",
				sequence: [60, 72],
				sequenceLabels: ["C", "C"],
				highlightKeys: [60, 72],
				image: "/courses/interval-ear.svg",
				imageAlt: "Four common intervals: octave, fifth, major 3rd, minor 3rd",
			},
			{
				id: "3",
				type: "play-sequence",
				title: "5th: C → G",
				body: "Strong and open. Like 'Twinkle twinkle'.",
				sequence: [60, 67],
				sequenceLabels: ["C", "G"],
				highlightKeys: [60, 67],
				image: "/courses/interval-ear.svg",
				imageAlt: "Four common intervals: octave, fifth, major 3rd, minor 3rd",
			},
			{
				id: "4",
				type: "play-sequence",
				title: "Major 3rd: C → E",
				body: "Bright. Happy.",
				sequence: [60, 64],
				sequenceLabels: ["C", "E"],
				highlightKeys: [60, 64],
				image: "/courses/interval-ear.svg",
				imageAlt: "Four common intervals: octave, fifth, major 3rd, minor 3rd",
			},
			{
				id: "5",
				type: "play-sequence",
				title: "Minor 3rd: C → E♭",
				body: "Sadder. Drop the E down a half step.",
				sequence: [60, 63],
				sequenceLabels: ["C", "E♭"],
				highlightKeys: [60, 63],
				image: "/courses/interval-ear.svg",
				imageAlt: "Four common intervals: octave, fifth, major 3rd, minor 3rd",
			},
		],
	},

	// ── INTERVALS: Octaves ───────────────────────────────────────────
	{
		id: "intervals-octaves",
		category: "intervals",
		title: "Octaves",
		description: "Same note, doubled.",
		estimatedMinutes: 3,
		summary: ["An octave = same letter, double the frequency", "Played C across three octaves", "Doubled a note in two octaves for a thicker sound"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Same note, higher",
				body: "An octave higher = the same letter, sounding 'the same' but brighter.",
				image: "/courses/octave-three-cs.svg",
				imageAlt: "C2, C4, and C6 — the same note three octaves apart",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Three Cs",
				body: "Low, middle, high.",
				sequence: [36, 60, 84],
				sequenceLabels: ["C2", "C4", "C6"],
				highlightKeys: [36, 60, 84],
				image: "/courses/octave-three-cs.svg",
				imageAlt: "C2, C4, and C6 — the same note three octaves apart",
			},
			{
				id: "3",
				type: "play-chord",
				title: "Double a note",
				body: "C and C an octave higher, together.",
				midis: [60, 72],
				chordName: "C octave",
				highlightKeys: [60, 72],
				image: "/courses/octave-three-cs.svg",
				imageAlt: "C2, C4, and C6 — the same note three octaves apart",
			},
		],
	},

	// ── IMPROVISATION: C Major ───────────────────────────────────────
	{
		id: "improvisation-in-c-major",
		category: "improvisation",
		title: "Improvise in C Major",
		description: "Backing track loops C – Am – F – G.",
		estimatedMinutes: 5,
		summary: [
			"Stay on white keys above middle C — no wrong notes",
			"Backing loop: C – Am – F – G",
			"End phrases on C, E, or G for a 'resolved' feeling",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "No wrong notes",
				body: "Stay on white keys and everything fits.",
				image: "/courses/backing-loop-c-am-f-g.svg",
				imageAlt: "Backing chord loop — C, Am, F, G",
			},
			{
				id: "2",
				type: "text",
				title: "Your scale",
				body: "All white keys above middle C.",
				highlightKeys: whiteKeysInRange(60, 108),
				image: "/courses/backing-loop-c-am-f-g.svg",
				imageAlt: "Backing chord loop — C, Am, F, G",
			},
			{
				id: "3",
				type: "play-any-of",
				title: "Try the scale",
				body: "Press 8 white keys, any order.",
				allowedMidis: whiteKeysInRange(60, 84),
				hitsNeeded: 8,
				highlightKeys: C_MAJOR_SCALE,
				demoNotes: C_MAJOR_SCALE,
				demoNoteDurationMs: 400,
				demoGapMs: 120,
				image: "/courses/backing-loop-c-am-f-g.svg",
				imageAlt: "Backing chord loop — C, Am, F, G",
			},
			{
				id: "4",
				type: "text",
				title: "Tips",
				body: "Start slow. End phrases on C, E, or G. Repeat ideas.",
				highlightKeys: C_MAJOR_SCALE,
				image: "/courses/backing-loop-c-am-f-g.svg",
				imageAlt: "Backing chord loop — C, Am, F, G",
			},
			{
				id: "5",
				type: "improvisation",
				title: "Improvise!",
				body: "Backing loops C – Am – F – G. Play any white keys above middle C.",
				bpm: 80,
				beatsPerChord: 4,
				chords: [
					{ name: "C", midis: C_MAJOR },
					{ name: "Am", midis: A_MINOR },
					{ name: "F", midis: F_MAJOR },
					{ name: "G", midis: G_MAJOR },
				],
				scaleMidis: whiteKeysInRange(60, 108),
				loopCount: null,
				highlightKeys: whiteKeysInRange(60, 108),
				image: "/courses/backing-loop-c-am-f-g.svg",
				imageAlt: "Backing chord loop — C, Am, F, G",
			},
		],
	},

	// ── IMPROVISATION: A Minor ───────────────────────────────────────
	{
		id: "improvisation-a-minor",
		category: "improvisation",
		title: "Improvise in A Minor",
		description: "Same white keys, sad mood.",
		estimatedMinutes: 4,
		summary: [
			"Same white keys as C major, but starting on Am sounds sad",
			"Backing loop: Am – F – C – G",
			"Ending phrases on A gives a 'sad-resolved' feel",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Sad scale",
				body: "Same white keys as C major. Backing track starts on Am — sounds sad.",
				highlightKeys: A_NATURAL_MINOR_SCALE,
				image: "/courses/backing-loop-am-f-c-g.svg",
				imageAlt: "Backing chord loop — Am, F, C, G",
			},
			{
				id: "2",
				type: "text",
				title: "End on A",
				body: "For a 'sad-resolved' feel, end your phrases on A.",
				highlightKeys: A_NATURAL_MINOR_SCALE,
				image: "/courses/backing-loop-am-f-c-g.svg",
				imageAlt: "Backing chord loop — Am, F, C, G",
			},
			{
				id: "3",
				type: "improvisation",
				title: "Play!",
				body: "Backing loops Am – F – C – G. White keys only.",
				bpm: 76,
				beatsPerChord: 4,
				chords: [
					{ name: "Am", midis: A_MINOR },
					{ name: "F", midis: F_MAJOR },
					{ name: "C", midis: C_MAJOR },
					{ name: "G", midis: G_MAJOR },
				],
				scaleMidis: whiteKeysInRange(60, 108),
				loopCount: null,
				highlightKeys: whiteKeysInRange(60, 108),
				image: "/courses/backing-loop-am-f-c-g.svg",
				imageAlt: "Backing chord loop — Am, F, C, G",
			},
		],
	},

	// ── IMPROVISATION: Pentatonic ────────────────────────────────────
	{
		id: "improvisation-pentatonic",
		category: "improvisation",
		title: "Pentatonic Improv",
		description: "5 safe notes.",
		estimatedMinutes: 4,
		summary: ["Stick to the 5 pentatonic notes: C D E G A", "Every note sounds 'right' over the backing track", "Improvised over C – Am – F – G"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Only 5 notes",
				body: "C D E G A. Cannot go wrong.",
				highlightKeys: C_MAJOR_PENTATONIC,
				image: "/courses/pentatonic-scale.svg",
				imageAlt: "C major pentatonic — C D E G A",
			},
			{
				id: "2",
				type: "improvisation",
				title: "Play!",
				body: "Backing loops C – Am – F – G. Stick to the highlighted notes.",
				bpm: 88,
				beatsPerChord: 4,
				chords: [
					{ name: "C", midis: C_MAJOR },
					{ name: "Am", midis: A_MINOR },
					{ name: "F", midis: F_MAJOR },
					{ name: "G", midis: G_MAJOR },
				],
				scaleMidis: [60, 62, 64, 67, 69, 72, 74, 76, 79, 81, 84, 86, 88, 91, 93],
				loopCount: null,
				highlightKeys: [60, 62, 64, 67, 69, 72, 74, 76, 79, 81, 84, 86, 88, 91, 93],
				image: "/courses/pentatonic-scale.svg",
				imageAlt: "C major pentatonic — C D E G A",
			},
		],
	},

	// ── IMPROVISATION: Blues ─────────────────────────────────────────
	{
		id: "improvisation-blues",
		category: "improvisation",
		title: "Blues Improv",
		description: "6 notes with attitude.",
		estimatedMinutes: 4,
		summary: [
			"Blues scale: C E♭ F G♭ G B♭ C — 6 notes plus the 'blue' G♭",
			"Use the blue note sparingly — lean and slide off it",
			"Improvised over a C – F – C – G blues progression",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "The blues scale",
				body: "C E♭ F G♭ G B♭ C. The G♭ is the 'blue' note.",
				highlightKeys: C_BLUES_SCALE,
				image: "/courses/blues-scale.svg",
				imageAlt: "C blues scale — the pink G♭ is the blue note",
			},
			{
				id: "2",
				type: "play-sequence",
				title: "Walk it",
				body: "Up the scale.",
				sequence: C_BLUES_SCALE,
				sequenceLabels: ["C", "E♭", "F", "G♭", "G", "B♭", "C"],
				highlightKeys: C_BLUES_SCALE,
				image: "/courses/blues-scale.svg",
				imageAlt: "C blues scale — the pink G♭ is the blue note",
			},
			{
				id: "3",
				type: "improvisation",
				title: "Play!",
				body: "Backing C – F – C – G. Use the blue note sparingly.",
				bpm: 84,
				beatsPerChord: 4,
				chords: [
					{ name: "C", midis: C_DOM7 },
					{ name: "F", midis: F_DOM7 },
					{ name: "C", midis: C_DOM7 },
					{ name: "G", midis: G_DOM7 },
				],
				scaleMidis: [60, 63, 65, 66, 67, 70, 72, 75, 77, 78, 79, 82, 84],
				loopCount: null,
				highlightKeys: [60, 63, 65, 66, 67, 70, 72, 75, 77, 78, 79, 82, 84],
				image: "/courses/blues-scale.svg",
				imageAlt: "C blues scale — the pink G♭ is the blue note",
			},
		],
	},

	// ── EAR TRAINING: Up or Down ─────────────────────────────────────
	{
		id: "ear-up-or-down",
		category: "ear_training",
		title: "Up or Down",
		description: "Two notes — did the second one go higher or lower?",
		estimatedMinutes: 4,
		summary: ["Trained the ear to spot which direction the pitch moved", "Worked from small steps to wide leaps", "No visual hints — sound only"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Listen with your ears, not your eyes",
				body: "I'll play two notes. Tell me if the second one is higher or lower than the first.",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "2",
				type: "ear-training",
				title: "Round 1 — easy",
				body: "Two notes. The keyboard won't show anything. Just listen.",
				notes: [60, 64],
				options: [
					{ id: "up", label: "Up ↑" },
					{ id: "down", label: "Down ↓" },
				],
				correctOptionId: "up",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "3",
				type: "ear-training",
				title: "Round 2",
				body: "Listen carefully.",
				notes: [67, 60],
				options: [
					{ id: "up", label: "Up ↑" },
					{ id: "down", label: "Down ↓" },
				],
				correctOptionId: "down",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "4",
				type: "ear-training",
				title: "Round 3 — closer notes",
				body: "Smaller step this time.",
				notes: [62, 64],
				options: [
					{ id: "up", label: "Up ↑" },
					{ id: "down", label: "Down ↓" },
				],
				correctOptionId: "up",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "5",
				type: "ear-training",
				title: "Round 4",
				body: "",
				notes: [69, 67],
				options: [
					{ id: "up", label: "Up ↑" },
					{ id: "down", label: "Down ↓" },
				],
				correctOptionId: "down",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "6",
				type: "ear-training",
				title: "Round 5 — wide leap",
				body: "Big jump now.",
				notes: [60, 72],
				options: [
					{ id: "up", label: "Up ↑" },
					{ id: "down", label: "Down ↓" },
				],
				correctOptionId: "up",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "7",
				type: "ear-training",
				title: "Round 6",
				body: "",
				notes: [76, 65],
				options: [
					{ id: "up", label: "Up ↑" },
					{ id: "down", label: "Down ↓" },
				],
				correctOptionId: "down",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
			{
				id: "8",
				type: "text",
				title: "Well done",
				body: "Your ear is starting to track pitch direction. Keep going.",
				image: "/courses/ear-up-down.svg",
				imageAlt: "First note vs second note — pitch goes up (↑) or down (↓)",
			},
		],
	},

	// ── EAR TRAINING: Same or Different ──────────────────────────────
	{
		id: "ear-same-or-different",
		category: "ear_training",
		title: "Same or Different",
		description: "Are these two notes the same pitch?",
		estimatedMinutes: 3,
		summary: [
			"Practised hearing whether two notes share the same pitch",
			"Some pairs were identical, others very close",
			"Trained sharp listening for unison",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Same or different?",
				body: "Two notes. Decide if they're the same pitch or different.",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
			{
				id: "2",
				type: "ear-training",
				title: "Round 1",
				body: "",
				notes: [60, 60],
				options: [
					{ id: "same", label: "Same" },
					{ id: "different", label: "Different" },
				],
				correctOptionId: "same",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
			{
				id: "3",
				type: "ear-training",
				title: "Round 2",
				body: "",
				notes: [64, 65],
				options: [
					{ id: "same", label: "Same" },
					{ id: "different", label: "Different" },
				],
				correctOptionId: "different",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
			{
				id: "4",
				type: "ear-training",
				title: "Round 3",
				body: "",
				notes: [67, 67],
				options: [
					{ id: "same", label: "Same" },
					{ id: "different", label: "Different" },
				],
				correctOptionId: "same",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
			{
				id: "5",
				type: "ear-training",
				title: "Round 4 — sneaky",
				body: "Listen closely.",
				notes: [69, 70],
				options: [
					{ id: "same", label: "Same" },
					{ id: "different", label: "Different" },
				],
				correctOptionId: "different",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
			{
				id: "6",
				type: "ear-training",
				title: "Round 5",
				body: "",
				notes: [72, 72],
				options: [
					{ id: "same", label: "Same" },
					{ id: "different", label: "Different" },
				],
				correctOptionId: "same",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
			{
				id: "7",
				type: "text",
				title: "Nice ears",
				body: "Unison is harder than it sounds. Good work.",
				image: "/courses/ear-same-different.svg",
				imageAlt: "Same pitch (=) vs different pitch (≠)",
			},
		],
	},

	// ── EAR TRAINING: Major or Minor ─────────────────────────────────
	{
		id: "ear-major-or-minor",
		category: "ear_training",
		title: "Major or Minor",
		description: "Happy or sad? Tell me what kind of chord you hear.",
		estimatedMinutes: 4,
		summary: ["Practised identifying major vs minor chords by ear", "Major chords sound bright and happy", "Minor chords sound darker, sadder"],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Major = happy, Minor = sad",
				body: "I'll play one chord at a time. Tell me if it's major (bright) or minor (dark).",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "2",
				type: "ear-training",
				title: "Round 1",
				body: "",
				notes: [60, 64, 67],
				isChord: true,
				options: [
					{ id: "major", label: "Major (happy)" },
					{ id: "minor", label: "Minor (sad)" },
				],
				correctOptionId: "major",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "3",
				type: "ear-training",
				title: "Round 2",
				body: "",
				notes: [57, 60, 64],
				isChord: true,
				options: [
					{ id: "major", label: "Major (happy)" },
					{ id: "minor", label: "Minor (sad)" },
				],
				correctOptionId: "minor",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "4",
				type: "ear-training",
				title: "Round 3",
				body: "",
				notes: [65, 69, 72],
				isChord: true,
				options: [
					{ id: "major", label: "Major (happy)" },
					{ id: "minor", label: "Minor (sad)" },
				],
				correctOptionId: "major",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "5",
				type: "ear-training",
				title: "Round 4",
				body: "",
				notes: [62, 65, 69],
				isChord: true,
				options: [
					{ id: "major", label: "Major (happy)" },
					{ id: "minor", label: "Minor (sad)" },
				],
				correctOptionId: "minor",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "6",
				type: "ear-training",
				title: "Round 5",
				body: "",
				notes: [67, 71, 74],
				isChord: true,
				options: [
					{ id: "major", label: "Major (happy)" },
					{ id: "minor", label: "Minor (sad)" },
				],
				correctOptionId: "major",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "7",
				type: "ear-training",
				title: "Round 6",
				body: "",
				notes: [64, 67, 71],
				isChord: true,
				options: [
					{ id: "major", label: "Major (happy)" },
					{ id: "minor", label: "Minor (sad)" },
				],
				correctOptionId: "minor",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
			{
				id: "8",
				type: "text",
				title: "Bright vs dark",
				body: "You can now hear the difference between a major and a minor chord. That's the most important ear-training skill in all of music.",
				image: "/courses/ear-major-minor.svg",
				imageAlt: "Major chords sound happy · minor chords sound sad",
			},
		],
	},

	// ── EAR TRAINING: Interval Size ──────────────────────────────────
	{
		id: "ear-interval-size",
		category: "ear_training",
		title: "Close or Far",
		description: "Were those notes close together or far apart?",
		estimatedMinutes: 4,
		summary: [
			"Practised judging interval distance by ear",
			"Close = a step or two; far = a leap of a 5th or more",
			"Foundation for naming specific intervals later",
		],
		steps: [
			{
				id: "1",
				type: "text",
				title: "Close or far?",
				body: "Two notes again. Tell me if they're close (a step or two) or far apart (a big leap).",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "2",
				type: "ear-training",
				title: "Round 1",
				body: "",
				notes: [60, 62],
				options: [
					{ id: "close", label: "Close" },
					{ id: "far", label: "Far" },
				],
				correctOptionId: "close",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "3",
				type: "ear-training",
				title: "Round 2",
				body: "",
				notes: [60, 72],
				options: [
					{ id: "close", label: "Close" },
					{ id: "far", label: "Far" },
				],
				correctOptionId: "far",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "4",
				type: "ear-training",
				title: "Round 3",
				body: "",
				notes: [64, 67],
				options: [
					{ id: "close", label: "Close" },
					{ id: "far", label: "Far" },
				],
				correctOptionId: "close",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "5",
				type: "ear-training",
				title: "Round 4",
				body: "",
				notes: [60, 76],
				options: [
					{ id: "close", label: "Close" },
					{ id: "far", label: "Far" },
				],
				correctOptionId: "far",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "6",
				type: "ear-training",
				title: "Round 5",
				body: "",
				notes: [69, 71],
				options: [
					{ id: "close", label: "Close" },
					{ id: "far", label: "Far" },
				],
				correctOptionId: "close",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "7",
				type: "ear-training",
				title: "Round 6",
				body: "",
				notes: [55, 72],
				options: [
					{ id: "close", label: "Close" },
					{ id: "far", label: "Far" },
				],
				correctOptionId: "far",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
			{
				id: "8",
				type: "text",
				title: "Distance trained",
				body: "Once your ear can tell close from far, naming specific intervals (3rd, 5th, octave) comes naturally.",
				image: "/courses/ear-close-far.svg",
				imageAlt: "Close = a step · Far = a wide leap",
			},
		],
	},
];

export function getAllCourses(): Course[] {
	return COURSES_LIST;
}

export function getCourseById(id: string): Course | undefined {
	return COURSES_LIST.find((c) => c.id === id);
}
