import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lobster } from "next/font/google";
import "./globals.css";
import { AudioEngineProvider } from "@/components/providers/AudioEngineProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lobster = Lobster({
  variable: "--font-lobster",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Away",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/icons/logo.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${lobster.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AudioEngineProvider>{children}</AudioEngineProvider>
      </body>
    </html>
  );
}
